# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-19 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161106_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('courseview_all', 'Can see all page'), ('courseview_no', 'cannot see this page')), 'verbose_name': '\u7528\u6237\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
    ]
