# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170419_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', validators=[users.validators.validate_file_extension]),
        ),
    ]
