# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-06-10 20:05
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20161210_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u7ec4\u7ec7\u8be6\u60c5'),
        ),
    ]
