# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-19 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20170419_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannercourse',
            options={'permissions': (('can see banner course', 'can see banner course'), ('cannot see banner course', 'cannot see banner course')), 'verbose_name': '\u8f6e\u64ad\u8bfe\u7a0b', 'verbose_name_plural': '\u8f6e\u64ad\u8bfe\u7a0b'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '\u7ae0\u8282', 'verbose_name_plural': '\u7ae0\u8282'},
        ),
    ]
